### ISSUE TITLE
[Question] Is this an ok implementation?

### ISSUE THREAD

**Issue by Industrial** [dominictarr/mux-demux#33]
Hi. I couldn't really think of another place to ask this so I'll ask here: I'm trying to encapsulate the marriage of Shoe, Mux-Demux and Dnode so that I can start an express + browserify based project, just require the network stack as module, init a Client or Server instance and have everything all set up.

https://gist.github.com/Industrial/c1a83cd8a1cd4556206a
1. Am I using the EventEmitter pattern correctly?
2. Is the error handling correct?
3. Would you add more/different methods/properties?
4. How would you expose the connection state as an API in the class?
5. Does shoe.js need a reconnect strategy or does it do that itself?
6. I'm not sure how I would support offline support in my app but that would be awesome to have even for (live) dashboards.

**Comment by dominictarr** [comment]
@Industrial shoe doesn't reconnect, use [reconnect](https://github.com/dominictarr/reconnect)
offline is not just a thing you can just "turn on" it depends a lot on what your application is 

this error handling might work. You should write tests that check dnode callbacks get passed errors if shoe disconnects before it's called back.

Actually, I think you should remove shoe from this. That will make testing much easier. Having rpc combined with multiplexed streams is very useful, but don't couple that to a specific networking layer. It's much better to create a stream and attach that to the network your self. That way, it can be used with *any* network that implements (or has a polyfil to) a stream (tcp, bluetooth, webrtc, etc)

you should publish this as it's own module.

Btw, I have something very similar to this implemented over here,
except using [pull-stream](https://github.com/dominictarr/pull-stream)
https://github.com/ssbc/muxrpc
